### ISSUE TITLE
Support multiple shas

### ISSUE THREAD

**Issue by juan-medina** [reasec/certificate-pinning-spring-web-client#2]
We need to support a list of valid shas, this will allow to have different shas for different public keys in different certificates.

This may be useful if the server has more than one certificate or is planning to do it so, for example when the keys are compromised or because if has a key rotation policy.

**Comment by juan-medina** [comment]
The current implementation to generate a WebClient it is:

```java
CertificatePinningWebClient.builder(githubApiPublicKeySha);
```
This will generate a spring `WebClient.Builder' allowing us to complete the construction of the client with the rest of the builders method provide by Spring.

```java
final WebClient webClient = CertificatePinningWebClient.builder(githubApiPublicKeySha)
        .baseUrl(GITHUB_API_URL)
        .build();
```
However to generate a client that support multiple shas we need to have a different method.

We could convert our constructor a Builder itself but them we will generate a build of a build looking not great:

```java
final WebClient webClient = CertificatePinningWebClient.builder()
        .withSha(SHA1)
        .withSha(SHA2)
        .withSha(SHA3)
        .build()
        .baseUrl(GITHUB_API_URL)
        .build();
```
We could change the semantics to make it a bit nicer 

```java
final WebClient webClient = CertificatePinningWebClient.create()
        .withSha(SHA1)
        .withSha(SHA2)
        .withSha(SHA3)
        .builder()
        .baseUrl(GITHUB_API_URL)
        .build();
```
However there is other alternatives, one is using lambdas, as the reactor client works:

```java
final WebClient webClient = CertificatePinningWebClient.builder( pinningSpec -> {
        pinningSpec.addSha(SHA1)
        .addSha(SHA2)
        .addSha(SHA3);
         })
        .baseUrl(GITHUB_API_URL)
        .build();
```
or creating explicitly

```java
final WebClient webClient = CertificatePinningWebClient.builder(PinningSpec.builder()
        .addSha(SHA1)
        .addSha(SHA2)
        .addSha(SHA3)
        .build())
        .baseUrl(GITHUB_API_URL)
        .build();
```
or

```java
final PinningSpec pinningSpec = PinningSpec.builder()
        .addSha(SHA1)
        .addSha(SHA2)
        .addSha(SHA3)
        .build();

final WebClient webClient = CertificatePinningWebClient.builder(pinningSpec)
        .baseUrl(GITHUB_API_URL)
        .build();
```
A final option could be create a builder that inherit from webflux `WebClient.Builder` however need to minic the whole protocol, all methods and so, and them couple with their interface, I dont really like that idea.

@jabrena @victorherraiz  toughts?

**Comment by jabrena** [comment]
In terms of Builder pattern, I prefer this option:

``` java
final PinningSpec pinningSpec = PinningSpec.builder()
        .addSha(SHA1)
        .addSha(SHA2)
        .addSha(SHA3)
        .build();

final WebClient webClient = CertificatePinningWebClient.builder()
        .pinningSpec(pinningSpec)
        .baseUrl(GITHUB_API_URL)
        .build();
```

Than the previous implementation:

``` java
final PinningSpec pinningSpec = PinningSpec.builder()
        .addSha(SHA1)
        .addSha(SHA2)
        .addSha(SHA3)
        .build();

final WebClient webClient = CertificatePinningWebClient.builder(pinningSpec)
        .baseUrl(GITHUB_API_URL)
        .build();
```

**Comment by juan-medina** [comment]
@jabrena that implementation is confuse since the `builder` do not return a `WebClient.Builder` need to returns something else and them the method `. pinningSpec` need to return a `WebClient.Builder` make them kind of a `build` method.

The semantic problem here is that is really confuse to return a builder that generate a builder.

Maybe could work better like this:

```java
final PinningSpec pinningSpec = PinningSpec.builder()
        .addSha(SHA1)
        .addSha(SHA2)
        .addSha(SHA3)
        .build();

final WebClient webClient = CertificatePinningWebClient.fromSpec(pinningSpec)
        .baseUrl(GITHUB_API_URL)
        .build();
```
No really convinced neither

**Comment by jabrena** [comment]
If you observe, current syntax not follow the idea from Webclient syntax. 

**Example:**

``` java
return WebClient.builder()
                .baseUrl(MY_HOST)
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .filter(MY_FILTER)
                .build();
```

The object `CertificatePinningWebClient` requires the same syntax:

``` java
final WebClient webClient = CertificatePinningWebClient.builder()
        .baseUrl(GITHUB_API_URL)
        .fromSpec(pinningSpec)
        .build();
```

**Comment by juan-medina** [comment]
similar examples in http reactor netty client:

https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClient.java#L782

Lambda style

```java
public final HttpClient secure(Consumer<? super SslProvider.SslContextSpec> sslProviderBuilder) {
		return HttpClientSecure.secure(this, sslProviderBuilder);
	}
```

The way to use is lambda style

HttpClient.secure( sslProviderBuilder -> {} );

**Comment by jabrena** [comment]
But it is a worse syntax with that Lambda approach (It is less readable)

**Comment by juan-medina** [comment]
@jabrena the syntax is not the problem:

`WebClient.builder()` return `WebClient.Builder` class

In your syntax `CertificatePinningWebClient.builder()` can not return a `WebClient.Builder` class since it has not a `.pinningSpec(pinningSpec)` method, in need to return something else.

So imaging them that return a `CertificatePinningWebClientBuilder` class, then the method `pinningSpec` need to return a `WebClient.Builder` so you could do `baseUrl()`

So you are making the method `pinningSpec` to be like a `build()` since need to convert the `CertificatePinningWebClientBuilder`into a `WebClient.Builder`, with the right parameters and so, so it need to close the builder.

The semantic thing to do will be that the `CertificatePinningWebClientBuilder` has a `build` method make the code looking strange with two `builds()` invocations.

But since we are not go to agree by sure let @victorherraiz to contribute in the discussion

**Comment by juan-medina** [comment]
For now is going to work like this

```java
final CertificatePinningSpec spec = CertificatePinningSpec.Builder()
    .sha(PUBLIC_KEY_SHA)
    .sha(OTHER_KEY_SHA)
    .build();

final WebClient webClient = CertificatePinningWebClient.builder(spec)
        .baseUrl(API_URL)
        .build();
```
