### ISSUE TITLE
Initial design of a Kotlin DSL

### ISSUE THREAD

**Issue by juan-medina** [reasec/certificate-pinning-spring-web-client#3]
When #2 is complete we probably need to create a Kotlin DSL with the new features created

**Comment by juan-medina** [comment]
#2

**Comment by juan-medina** [comment]
Now we have 2 DSL

**For creating a CertificatePinningSpec**
```kotlin
val spec = certificatePinningSpec {
  sha(PUBLIC_KEY_SHA)
  sha(PUBLIC_KEY_ALTERNATIVE_SHA)
}
```
This can be use to create the builder

```kotlin
val webClient = CertificatePinningWebClient.builder(spec)
  .baseUrl(API_URL)
  .build()
```

**We have a second DSL to create directly the builder**
```kotlin
val webClient = certificatePinningWebClientBuilder {
  spec {
    sha(PUBLIC_KEY_SHA)
    sha(PUBLIC_KEY_ALTERNATIVE_SHA)
  }
}
.baseUrl(API_URL)
.build()
```

**Comment by juan-medina** [comment]
@victorherraiz @jabrena any feedback?

**Comment by jabrena** [comment]
The Builder pattern, need in the Constructor to pass the baseURL, because it is a mandatory parameter. Take a look the article from Joshua Bloch:
http://www.informit.com/articles/article.aspx?p=1216151&seqNum=2

**Comment by juan-medina** [comment]
The URL is not part of this component is part of spring WebClient.Builder and is even optional on that builder since you could use the method .uri on the client to fetch data make no sense what you are saying,

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.Builder.html#baseUrl-java.lang.String-

And this DSL not a builder, and is most look like as the article you link these, are not paramethers, are individual parts in a DSL kotlin style:

https://kotlinlang.org/docs/reference/type-safe-builders.html

example on spring

https://github.com/sdeleuze/spring-kotlin-functional/blob/master/src/main/kotlin/functional/Beans.kt

**Comment by jabrena** [comment]
Oki, in that case, I am agree with the design. :)
