### ISSUE TITLE
Change tests to use localhost

### ISSUE THREAD

**Issue by juan-medina** [reasec/certificate-pinning-spring-web-client#5]
Change tests to use localhost

**Comment by juan-medina** [comment]
this is done via de certs created on here:

[src/test/resources/certs](https://github.com/reasec/certificate-pinning-spring-web-client/tree/master/src/test/resources/certs)

This certs are 10 years long, there is a script to create new certs if required:

[src/test/resources/certs/gencert.sh](https://github.com/reasec/certificate-pinning-spring-web-client/blob/master/src/test/resources/certs/gencert.sh)

However certs needs to add to the keystore in other to run local test, doing something like:

```bash
sudo keytool -importkeystore -deststorepass changeit -noprompt -destkeystore ${JAVA_HOME}/jre/lib/security/cacerts -srckeystore src/test/resources/certs/certificate.p12 -srcstoretype pkcs12 -srcstorepass password -alias selfsigned
```
This is doing authomaticaly on travis-ci, check the build file:

[.travis.yml](https://github.com/reasec/certificate-pinning-spring-web-client/blob/master/.travis.yml)

Test have been modified to to have a fake application using the service

[src/test/resources/application.yml](https://github.com/reasec/certificate-pinning-spring-web-client/blob/master/src/test/resources/application.yml)
[src/test/kotlin/com/reasec/certificatepinning/TestApplication.kt](https://github.com/reasec/certificate-pinning-spring-web-client/blob/master/src/test/kotlin/com/reasec/certificatepinning/TestApplication.kt)

@jabrena anything you like to discuss about this?

**Comment by jabrena** [comment]
What is the description for this issue?
I can not follow your ideas if you don't describe the issues that you create.

**Comment by juan-medina** [comment]
?? you just change a capital in the description is was there...

**Comment by juan-medina** [comment]
The ideas simple enough, in the past the test using github API now use a fake service running in localhost so it will work always

**Comment by jabrena** [comment]
Reviewed:
https://github.com/reasec/certificate-pinning-spring-web-client/commit/6debd1e4252d8801f6b268ac12bff83a91675807

It is Ok
